#!/usr/bin/env bash
# Print a Helm values overlay that pins every image in values.yaml to its
# current registry digest. Run on the operator's machine; pipe the output
# to a file and pass it as an extra `-f` to `helm install`/`helm upgrade`:
#
#   scripts/pin-digests.sh > pins.yaml
#   helm install ... -f values.yaml -f pins.yaml
#
# The chart's `nextcloud-stack.image` helper prefers `digest:` over `tag:`
# when both are set — so this overlay disables tag-mutation as a source
# (re-pulls only when digest changes, regardless of `imagePullPolicy`).
#
# Requires:
#   - crane    https://github.com/google/go-containerregistry
#              (`go install github.com/google/go-containerregistry/cmd/crane@latest`)
#   - yq       https://github.com/mikefarah/yq
#
# The default images are public. For a private/auth'd registry (e.g. the DHI
# overlay, dhi.io): `crane auth login <registry>` first, and run with that file:
#   scripts/pin-digests.sh values-dhi.yaml > pins-dhi.yaml

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHART_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VALUES_FILE="${1:-$CHART_ROOT/values.yaml}"

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1" >&2; exit 1; }; }
need crane
need yq

# yq paths to every image block referenced by templates.
PATHS=(
  .nextcloud.image
  .nextcloud.web.image
  .nextcloud.kubectl.image
  .postgres.image
  .valkey.image
  .clamav.image
  .cloudflare.tunnel.image
  .tests.image
)

OUT=$(mktemp); trap 'rm -f "$OUT"' EXIT
printf '{}\n' >"$OUT"

ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)
echo "# pin-digests.sh: resolving $(basename "$VALUES_FILE")" >&2
for p in "${PATHS[@]}"; do
  reg=$(yq -r "${p}.registry // \"docker.io\"" "$VALUES_FILE")
  repo=$(yq -r "${p}.repository" "$VALUES_FILE")
  tag=$(yq -r "${p}.tag" "$VALUES_FILE")
  ref="$reg/$repo:$tag"
  printf "  %s ... " "$ref" >&2
  if ! digest=$(crane digest "$ref" 2>/dev/null); then
    echo "FAILED (registry auth?)" >&2
    exit 1
  fi
  echo "$digest" >&2
  yq -i "${p}.digest = \"$digest\"" "$OUT"
done

cat <<EOF
# Generated by scripts/pin-digests.sh at $ts
# Source: $(basename "$VALUES_FILE")
# Apply with:  helm install/upgrade ... -f values.yaml -f <this-file>
EOF
cat "$OUT"
